#Filtering Dataset to Perform Different Operation

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Messy_Employment_India_Dataset.csv to Messy_Employment_India_Dataset.csv

#Step 1: Load and Inspect the Dataset

In [ ]:
df = pd.read_csv("Messy_Employment_India_Dataset.csv")                                  # LOAD DATASET
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,NaN,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.0,102200.0,6/19/2028
1997,NaN,35 - 44,Masters,Education,NaN,low,NaN,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.0,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,NaN,43300.0,6/22/2028

In [ ]:
clean_df = df.copy()                                                                  #  COPY OF MAIN  DATASET.

In [ ]:
clean_df                                                                            # TO SEE COPY DATASET.

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,16.0,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,16.0,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,16.0,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.0,102200.0,6/19/2028
1997,NaN,35 - 44,Masters,Education,NaN,low,16.0,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.0,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,16.0,43300.0,6/22/2028

In [ ]:
clean_df.head()                                                                          # TO CHECK THE FIRST 5 ROW.

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023

#Step 2: Understand Dataset Structure and Data Types

In [ ]:
clean_df.head(4)                                                                          # TO CHECK THE FIRST 4 ROW.

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023

In [ ]:
clean_df.tail(4)                                                                          # TO CHECK THE LAST 4 ROW.

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.0,102200.0,6/19/2028
1997,NaN,35 - 44,Masters,Education,NaN,low,NaN,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.0,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,NaN,43300.0,6/22/2028

In [ ]:
clean_df.info()                                                                           # TO CHECK THE DATA INFO.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                1732 non-null   object
 1   Age Group             1768 non-null   object
 2   Education             1804 non-null   object
 3   Industry              1799 non-null   object
 4   Location              1787 non-null   object
 5   AI Risk               1716 non-null   object
 6   Years of Experience   980 non-null    float64
 7   Monthly Salary (INR)  1613 non-null   float64
 8   Date Recorded         2000 non-null   object
dtypes: float64(2), object(7)
memory usage: 140.8+ KB

In [ ]:
clean_df.shape

(2000, 9)

In [ ]:
clean_df.describe()                                                                        # TO CHECK THE STATISTICAL DATA.

       Years of Experience  Monthly Salary (INR)        Date Recorded
count          2000.000000            2000.00000                 2000
mean             15.630000           76947.05000  2025-09-26 12:00:00
min               0.000000            5100.00000  2023-01-01 00:00:00
25%              16.000000           49150.00000  2024-05-14 18:00:00
50%              16.000000           77200.00000  2025-09-26 12:00:00
75%              16.000000          104125.00000  2027-02-08 06:00:00
max              30.000000          149900.00000  2028-06-22 00:00:00
std               6.382278           37382.13816                  NaN

In [ ]:
clean_df.dtypes                                                                          # TO CHECK THE DATA TYPES.

Status                   object
Age Group                object
Education                object
Industry                 object
Location                 object
AI Risk                  object
Years of Experience     float64
Monthly Salary (INR)    float64
Date Recorded            object
dtype: object

In [ ]:
clean_df.columns                                                                          # TO PRINT THE COLUMNS.

Index(['Status', 'Age Group', 'Education', 'Industry', 'Location', 'AI Risk',
       'Years of Experience', 'Monthly Salary (INR)', 'Date Recorded'],
      dtype='object')

In [ ]:
clean_df.sample()                                                                          # TO CHECK RANDOM ROW.

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
1911,NaN,35 - 44,Master,Retail,NaN,Medium,NaN,32600.0,3/26/2028

#Step 3: Identify and Handle Missing Values

In [ ]:
clean_df.isnull()                                                                           # TO CEHCK MISSING VALUES.

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,False,False,False,False,False,True,True,False,False
1,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
1995,False,False,False,False,False,False,True,False,False
1996,False,False,False,False,True,True,False,False,False
1997,True,False,False,False,True,False,True,False,False
1998,False,False,False,False,False,False,False,False,False
1999,False,False,False,True,True,False,True,False,False

In [ ]:
clean_df.isnull().sum()                                                                   # TO CHECK COUNT OF MISSING VALUES.

Status                   268
Age Group                232
Education                196
Industry                 201
Location                 213
AI Risk                  284
Years of Experience     1020
Monthly Salary (INR)     387
Date Recorded              0
dtype: int64

In [ ]:
clean_df['Years of Experience'] = clean_df['Years of Experience'].fillna(           # FILL NUMERICAL COLUMNS WITH MEDIAN.
    clean_df['Years of Experience'].median())


clean_df['Monthly Salary (INR)'] = clean_df['Monthly Salary (INR)'].fillna(
    clean_df['Monthly Salary (INR)'].median())

In [ ]:
categorical_cols = [                                                                 # TO FILL THE ALPHABATE VALUE WE USE CATEGORICAL WITH MODE.
    'Status',
    'Age Group',
    'Education',
    'Industry',
    'Location',
    'AI Risk'
]
for col in categorical_cols:
    clean_df[col] = clean_df[col].fillna(clean_df[col].mode()[0])

In [ ]:
clean_df.isnull().sum()                                                             # CHECK AGAIN AFTER THE FILL VALUES.

Status                  0
Age Group               0
Education               0
Industry                0
Location                0
AI Risk                 0
Years of Experience     0
Monthly Salary (INR)    0
Date Recorded           0
dtype: int64

In [ ]:
clean_df                                                                                # NOW DATA IS GOOD ATER FILL NULL VALUES.

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,HIGH,16.0,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,16.0,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,Employed,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,16.0,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,Bangalore,HIGH,22.0,102200.0,6/19/2028
1997,Employed,35 - 44,Masters,Education,Bangalore,low,16.0,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.0,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,Retail,Bangalore,moderate,16.0,43300.0,6/22/2028

#Step 4: Remove Duplicate Records

In [ ]:
clean_df.duplicated()                                                                  # TO CHECK THE DUPLICATE VALUE.

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

In [ ]:
clean_df.duplicated().sum()                                                             # TO CHECK COUNT OF DUPLICATE VALUES.

np.int64(0)

#Step 5: Correct Inconsistent Formatting and Text Values

In [ ]:
text_columns = ['Status', 'Education', 'Industry', 'Location', 'AI Risk']               # TO REMOVE EXTRA SPACE(.str.strip())  AND FOR CONVERT FIRST LETTER CAPITAL(.str.title())

for col in text_columns:
    clean_df[col] = clean_df[col].str.strip().str.title()

In [ ]:
clean_df['Education'] = clean_df['Education'].replace({                                 # TO CORRECT THE WORD WE REPLACE THE WORD.
    'Phd': 'PhD'
})

In [ ]:
clean_df['Age Group'] = clean_df['Age Group'].str.replace('_', '-')                     # TO HANDEL THE SPACE BETWEEN NUMBER.

In [ ]:
clean_df

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,Employed,25-34,High School,Technology,Urban,High,16.0,40700.0,1/1/2023
1,Employed,18-24,Diploma,Fintech,Rural,Moderate,16.0,17500.0,1/2/2023
2,Employed,25-34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,Unemployed,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,Employed,45-54,Diploma,Fintech,Hyderabad,Low,9.0,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1995,Employed,25-34,Ph.D,Finance,Hyderabad,Low,16.0,113000.0,6/18/2028
1996,Employed,25-34,PhD,Tech,Bangalore,High,22.0,102200.0,6/19/2028
1997,Employed,35 - 44,Masters,Education,Bangalore,Low,16.0,31600.0,6/20/2028
1998,Employed,25-34,High School,Retail,Mumbai,High,22.0,92500.0,6/21/2028
1999,Unemployed,25-34,High School,Retail,Bangalore,Moderate,16.0,43300.0,6/22/2028

#Step 6: Fix Data Type Issues

In [ ]:
clean_df.dtypes                                                                          # DATE RECORDED IN OBJECT TYPE

Status                   object
Age Group                object
Education                object
Industry                 object
Location                 object
AI Risk                  object
Years of Experience     float64
Monthly Salary (INR)    float64
Date Recorded            object
dtype: object

In [ ]:
clean_df['Date Recorded'] = pd.to_datetime(clean_df['Date Recorded'])

In [ ]:
clean_df.dtypes                                                                          # NOW DATE RECORDED IN DATETIME TYPE

Status                          object
Age Group                       object
Education                       object
Industry                        object
Location                        object
AI Risk                         object
Years of Experience            float64
Monthly Salary (INR)           float64
Date Recorded           datetime64[ns]
dtype: object

#Step 7: Detect and Handle Outliers

In [ ]:
clean_df['Monthly Salary (INR)'].describe()                                             # TO CHECK THE OUTLIERS IN DATA

count      2000.00000
mean      76947.05000
std       37382.13816
min        5100.00000
25%       49150.00000
50%       77200.00000
75%      104125.00000
max      149900.00000
Name: Monthly Salary (INR), dtype: float64

#Step 8: Rename and Standardize Column Names

In [ ]:
clean_df.columns = (                                                                     # TO RENAME THE COLUMNS.
    clean_df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("(", "", regex=False)
      .str.replace(")", "", regex=False)
)

In [ ]:
print(clean_df.columns.tolist())                                                        # TO PRINT THE COLUMNS AFTER THE CHANGE.

['status', 'age_group', 'education', 'industry', 'location', 'ai_risk', 'years_of_experience', 'monthly_salary_inr', 'date_recorded']

#Step 9: Validate and Verify Cleaned Data.

In [ ]:
clean_df.isnull().sum()                                                                 # TO CHECK THE MISSING VALUES AFTER CLEAN DATA

status                 0
age_group              0
education              0
industry               0
location               0
ai_risk                0
years_of_experience    0
monthly_salary_inr     0
date_recorded          0
dtype: int64

In [ ]:
clean_df.duplicated().sum()                                                             # TO CHECK THE DUPLICATE VALUES AFTER CLEAN DATA

np.int64(0)

In [ ]:
clean_df.dtypes

status                         object
age_group                      object
education                      object
industry                       object
location                       object
ai_risk                        object
years_of_experience           float64
monthly_salary_inr            float64
date_recorded          datetime64[ns]
dtype: object

In [ ]:
clean_df.columns.tolist()                                                               # TO PRINT THE COLUMNS AFTER CLEAN DATA

['status',
 'age_group',
 'education',
 'industry',
 'location',
 'ai_risk',
 'years_of_experience',
 'monthly_salary_inr',
 'date_recorded']

In [ ]:
clean_df.info()                                                                          # TO CHECK THE CLEAN DATA INFO.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   status               2000 non-null   object
 1   age_group            2000 non-null   object
 2   education            2000 non-null   object
 3   industry             2000 non-null   object
 4   location             2000 non-null   object
 5   ai_risk              2000 non-null   object
 6   years_of_experience  2000 non-null   float64
 7   monthly_salary_inr   2000 non-null   float64
 8   date_recorded        2000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 140.8+ KB

In [ ]:
clean_df.head(10)                                                                         # TO CHECK VALUE AFTER CLEAN

,status,age_group,education,industry,location,ai_risk,years_of_experience,monthly_salary_inr,date_recorded
0,Employed,25-34,High School,Technology,Urban,High,16.0,40700.0,2023-01-01
1,Employed,18-24,Diploma,Fintech,Rural,Moderate,16.0,17500.0,2023-01-02
2,Employed,25-34,High School,Retail,Delhi,Low,16.0,77600.0,2023-01-03
3,Unemployed,18-24,Masters,Retail,Urban,Low,30.0,100200.0,2023-01-04
4,Employed,45-54,Diploma,Fintech,Hyderabad,Low,9.0,19500.0,2023-01-05
5,Unemployed,25-34,PhD,Tech,Bangalore,High,16.0,54500.0,2023-01-06
6,Employed,35 - 44,Master,Retail,Mumbai,Moderate,20.0,136500.0,2023-01-07
7,Unemployed,35 - 44,Master,Retail,Rural,Low,28.0,25300.0,2023-01-08
8,Employed,35 - 44,Ph.D,Retail,Bangalore,Medium,0.0,103600.0,2023-01-09
9,Unemployed,55+,Ph.D,Tech,Bangalore,High,3.0,126500.0,2023-01-10

#Step 10: Export the Final Cleaned Dataset

In [ ]:
clean_df.to_csv("final_dataset.csv", index=False)

In [ ]:
print("final dataset exported successfully!")

final dataset exported successfully!